name = "Ascendant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0194c6d7154be0252cc62e2ca9c1fcb9f81cfc490e6d86edc88d03ab0c82487"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
