name = "Ascendant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bb8cea0f8f3a3809823103d7fea26754ddb36ab570e68a2a7e29aa4a1675af0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
