name = "Ascendant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb5958022a22d82c1bdb17d3da8eaf409fad4378cd929f5e866cf74d23aa9c71"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
